AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyComponent:
    Type: 'AWS::ImageBuilder::Component'
    Properties:
      Name: MyComponent
      Version: '1.0.0'
      Description: My custom component
      Platform: Linux
      Data: |
        name: MyComponent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: MyStep
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Hello, World!"
